- name: Servizio contenitore di Azure con Kubernetes
  href: ./index.yml
- name: Panoramica
  items:
    - name: Informazioni sul servizio contenitore
      href: container-service-intro-kubernetes.md
- name: Guide introduttive
  expanded: true
  items:
    - name: Linux con Kubernetes
      href: container-service-kubernetes-walkthrough.md
- name: Esercitazioni
  items:
    - name: '1: Creare immagini del contenitore'
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: '2: Creare un registro contenitori'
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: '3: Creare un cluster Kubernetes'
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: '4: Eseguire l''applicazione'
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: '5: Ridimensionare l''applicazione'
      href: container-service-tutorial-kubernetes-scale.md
    - name: '6: Aggiornare l''applicazione'
      href: container-service-tutorial-kubernetes-app-update.md
    - name: '7: Monitorare con OMS'
      href: container-service-tutorial-kubernetes-monitor.md
- name: Esempi
  items:
    - name: Interfaccia della riga di comando di Azure
      href: cli-samples.md
- name: Concetti
  items:
    - name: Proteggere i contenitori
      href: container-service-security.md
- name: Guide alle procedure
  items:
    - name: Kubernetes con Windows
      href: container-service-kubernetes-windows-walkthrough.md
    - name: Interfaccia Web di Kubernetes
      href: container-service-kubernetes-ui.md
    - name: Distribuire grafici Helm
      href: container-service-kubernetes-helm.md
    - name: Jenkins e Kubernetes ACS
      href: container-service-kubernetes-jenkins.md
    - name: Usare la bozza con il record di controllo di accesso e il servizio contenitore di Azure
      href: container-service-draft-up.md
    - name: Connettersi con un cluster del servizio contenitore di Azure
      href: container-service-connect.md
    - name: Ridimensionare un cluster del servizio contenitore di Azure
      href: container-service-scale.md
    - name: Monitorare
      items:
        - name: Monitorare con Datadog
          href: container-service-kubernetes-datadog.md
        - name: Monitorare con Sysdig
          href: container-service-kubernetes-sysdig.md
        - name: Monitorare con CoScale
          href: container-service-kubernetes-coscale.md
    - name: Distribuire app Spring Boot
      items:
        - name: Distribuire un'applicazione Spring Boot in Linux nel servizio contenitore di Azure
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Distribuire un'applicazione Spring Boot in un cluster Kubernetes nel servizio contenitore di Azure
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
- name: Riferimento
  items:
    - name: Interfaccia della riga di comando di Azure 2.0
      href: /cli/azure/acs
    - name: REST
      href: /rest/api/compute/containerservices
- name: Risorse
  items:
    - name: Roadmap per Azure
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Domande frequenti
      href: container-service-faq.md
    - name: Modelli - Motore ACS
      href: 'https://github.com/Azure/acs-engine'
    - name: Prezzi
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Aree di disponibilità
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Video
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'